[package]
name = "scopeguard"
version = "0.2.0"

license = "MIT/Apache-2.0"
repository = "https://github.com/bluss/scopeguard"
documentation = "https://bluss.github.io/scopeguard/"
authors = ["bluss"]

description = "A RAII scope guard."

keywords = ["scope-guard", "defer"]

